name: Validate source

on: [push, pull_request]

jobs:
  validate-source:
    name: Validate source
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
            !~/.cache/exclude
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Validate source
        run: npm run validate-source
