name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.9
          registry-url: https://registry.npmjs.org

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
            !~/.cache/exclude
          key: >
            ${{ runner.os }}
            -npm
            -${{ github.workflow }}
            -${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ github.workflow }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}

      - name: Install dependencies
        run: npm ci

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
