name: Validate source

on: push

jobs:
  validate-source:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout source

      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: 12.9

      - uses: actions/cache@v2
        name: Cache dependencies
        with:
          path: |
            ~/.npm
            ~/.cache
            !~/.cache/exclude
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Validate source
        run: npm run validate-source
